/*
 * XYZWriter.cpp
 *
 *  Created on: 01.03.2010
 *      Author: eckhardw
 */

#include "outputWriter/XYZWriter.h"
#include <iomanip>
#include <sstream>

using namespace std;

namespace outputWriter {

XYZWriter::XYZWriter() = default;

XYZWriter::~XYZWriter() = default;

void XYZWriter::plotParticles(std::list<Particle> particles,
                              const std::string &filename, int iteration) {
  std::ofstream file;
  stringstream strstr;
  strstr << filename << "_" << setfill('0') << setw(4) << iteration << ".xyz";

  file.open(strstr.str().c_str());
  file << particles.size() << endl;
  file << "Generated by MolSim. See http://openbabel.org/wiki/XYZ_(format) for "
          "file format doku."
       << endl;

  for (auto &p : particles) {
    std::array<double, 3> x = p.getX();
    file << "Ar ";
    file.setf(ios_base::showpoint);

    for (auto &xi : x) {
      file << xi << " ";
    }

    file << endl;
  }

  file.close();
}

} // namespace outputWriter
