/*
 * XYZWriter.cpp
 *
 *  Created on: 01.03.2010
 *      Author: eckhardw
 */

#include "outputWriter/XYZWriter.h"
#include <iomanip>
#include <sstream>
#include <vector>

namespace outputWriter {

    XYZWriter::XYZWriter() = default;

    XYZWriter::~XYZWriter() = default;

    void XYZWriter::plotParticles(ParticleContainer& container,
                                  const std::string &filename, int iteration) {
        std::ofstream file;
        std::stringstream strstr;
        strstr << filename << "_" << std::setfill('0') << std::setw(4) << iteration << ".xyz";

        file.open(strstr.str().c_str());
        file << container.size() << std::endl;
        file << "Generated by MolSim. See http://openbabel.org/wiki/XYZ_(format) for "
                "file format doku."
             << std::endl;

        for (const auto &p: container) {
            const auto &tmp = p.getX();
            std::array<double, 3> x = {tmp(0), tmp(1), tmp(2)};
            file << "Ar ";
            file.setf(std::ios_base::showpoint);

            for (auto &xi: x) {
                file << xi << " ";
            }

            file << std::endl;
        }

        file.close();
    }

} // namespace outputWriter
