// Not copyrighted - public domain.
//
// This sample parser implementation was generated by CodeSynthesis XSD,
// an XML Schema to C++ data binding compiler. You may use it in your
// programs without any restrictions.
//

#ifndef SIMULATION_SCHEMA_PIMPL_HXX
#define SIMULATION_SCHEMA_PIMPL_HXX

#include "simulation_schema-pskel.h"

class positionType_pimpl : public virtual positionType_pskel {
   public:
    virtual void pre();

    virtual void x(double);

    virtual void y(double);

    virtual void z(double);

    virtual void post_positionType();
};

class gridDimType_pimpl : public virtual gridDimType_pskel {
   public:
    virtual void pre();

    virtual void dimx(long long);

    virtual void dimy(long long);

    virtual void dimz(long long);

    virtual void post_gridDimType();
};

class velocityType_pimpl : public virtual velocityType_pskel {
   public:
    virtual void pre();

    virtual void x(double);

    virtual void y(double);

    virtual void z(double);

    virtual void post_velocityType();
};

class configuration_pimpl : public virtual configuration_pskel {
   public:
    virtual void pre();

    virtual void fps(long long);

    virtual void video_length(long long);

    virtual void delta_t(double);

    virtual void end_time(double);

    virtual void cuboid();

    virtual void post_configuration();
};

class cuboid_pimpl : public virtual cuboid_pskel {
   public:
    virtual void pre();

    virtual void position();

    virtual void grid_dim();

    virtual void grid_spacing(double);

    virtual void temperature(double);

    virtual void mass(double);

    virtual void velocity();

    virtual void type(long long);

    virtual void post_cuboid();
};

#endif  // SIMULATION_SCHEMA_PIMPL_HXX
