
#include "XYZWriter.h"

#include <iomanip>
#include <sstream>

void XYZWriter::writeFile(const std::string& output_dir_path, int iteration, const std::unique_ptr<ParticleContainer>& particle_container) const {
    auto filename = output_dir_path + "/" + "MD_XYZ";

    std::stringstream strstr;
    strstr << filename << "_" << std::setfill('0') << std::setw(4) << iteration << ".xyz";

    std::ofstream file;

    file.open(strstr.str().c_str());
    file << particle_container->size() << std::endl;
    file << "Generated by MolSim. See http://openbabel.org/wiki/XYZ_(format) for file format doku." << std::endl;

    for (auto& p : *particle_container) {
        std::array<double, 3> x = p.getX();
        file << "Ar ";
        file.setf(std::ios_base::showpoint);

        for (auto& xi : x) {
            file << xi << " ";
        }

        file << std::endl;
    }

    file.close();
}
