on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build with AddressSanitizer
        run: |
          cd $GITHUB_WORKSPACE
          mkdir build
          cd build
          export TERM=xterm
          cmake ..
          cd $GITHUB_WORKSPACE/build
          make CC=gcc CFLAGS=-fsanitize=address
     
      
      

