on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  test_memory_access:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.before }}

      - name: Test memory access errors
        run: |
          gcc -fsanitize=address -o pipelineOutput ./src/Molsim.cpp
          ./pipelineOutput

