on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  test_memory_access:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.before }}

      - name: Print Current Directory
        run: |
          pwd

      - name: Compile Molsim.cpp
        run: |
          cd $GITHUB_WORKSPACE
          ls
          cd src 
          ls
          gcc -fsanitize=address -o pipelineOutput src/Molsim.cpp
     
      
      

