on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      CC: gcc-10
      CXX: g++-10
      BUILD_TYPE: Release

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_C_FLAGS="-fsanitize=address" -DCMAKE_CXX_FLAGS="-fsanitize=address" -DCMAKE_LINKER_FLAGS="-fsanitize=address" -DCMAKE_BUILD_TYPE=${BUILD_TYPE} ..
          cmake --build . --config ${BUILD_TYPE}
        working-directory: ${{github.workspace}}

      - name: Run Tests
        run: ctest -C ${BUILD_TYPE}
        working-directory: ${{github.workspace}}/build
          
          
     
      
      

